services:
- docker
language: generic
before_install:
- docker build -t ${REPOSITORY} .
deploy:
  provider: script
  script: bash docker_push
env:
  global:
  - secure: PdNHEZ0bipdhFTMviF91Z70eJ4Idbrl7j1y5n2gHlgWo6MOl9xv5rbzXWHzvXo86Q8P2U0lIYkguwHDsk1ijT6Sf6xUTPlsaQajSn6VYDzoAmqIMHcNuM7QC2lbwznYsTqPzd0mE9PfwJMEcDWyYEfi1ZJpIWBAhqTOJQH/z/fYphX+D/fHk4IKigUqqf39NvkuvYABXQQCNeGAoSqwROS1FtyV1iqsaYcITuPTsAEzddWkFahocmKnJE0WDI5QqoSefxBnzo9StMZetj1NzLzwgmbdfq/rCmkUYksFO9vO06TjtmdlWF2owWbAI1+14YfZTHN/ya2V2VL9xit9udG8OY2Pqjtt0LKWD86WOuI2QM+zlcwzkakvTW6PgfLjkZRCujSQpgyQyWLxEMCOsHrxICXUkq9Fe5nm/1R8L6kRN6H9iDrDaBD+gduh0z9az9C3KAzj2mat2jsNgAV/kGkQWdSnQ/i7+q7nnRt5btngr58RfHVjLmY+8tKYEjY0SP8yJ+TkaMahPh3sufd6tRFM6L7QokJNya47U8f2WYmLkThFa7C3ADDpgPeNL4DMJBATfWWAO0sx7tER2j7mZMij032tPz0BaIuS+3cuYYMt8lGIRLGk/Br1eaXStSk4m96c/LI+wRm1YfZtT6np87srFrMSi22J9h5LZQvI8Mhc=
  - secure: IE84oVDXAaTwbx5M+oai2X4GIa3PB1isqude3PAlSOzLruckGizlOIX1khr2TzRWyAzaIPcVTQiZnxomtwSJcWcND6OQwx/mfk/4dpmYh1pcR8fJMC3g/hwiNZVKsrKse5VrNLtirilAB7qtOUzMNRX4KAtM2iKXv8Mv3/tRP3l49NzCm0UZ0tj/m0ctWVwurEg5w8mcKjkDVaY55h0vW3Ob9lR8abPtmN0J+7MCaeSY7JGp+hc1WDwjkVT1JrKmH1OY0FqZjsLytXlkUZX2JpQS3CQJpo3ci7B1RrDtsjTWiWPejwF1FLykE0OWg7Gq435EhSskmUxjV/UhxY3wwFC6HwRbZRTgWKvbD/MW+K6IEVPe5o1R2mPJ8fog8pYf23aqxIMPbkQlZ23330Jtb4bOU8Xbhi70YWBFOLk3iTEoSCzZU72K8hqOIP9QcT22lih/o2HOPwbklXdMeV1M5Rd99mG8ijFlXgQETegHzmPzQp7VcCVwj1kzjrSb3Px0WkB3x1SasXA78k3fMt1PU3YRZLhkKqwUdfOEIhMhjchDmnyEAStf4rHMiaXUN5+h0k4GrSYFVhGWcelq2hFH9FcQxoHeSvieXWmamQz+Om6atEdbj9DUo2Xftyj4E3hrTPD3TdeL6fUT0FGQkHLwFmVONrtFFeOzFVl4OFbztIM=
